import { validateOutreach } from './messageGuard.js';

function topIssues(audit) {
  const severity = { high: 3, medium: 2, low: 1 };
  return (audit.issues || []).slice().sort((a, b) => (severity[b.severity] || 0) - (severity[a.severity] || 0)).slice(0, 3).map(issue => issue.title.replace('Missing or weak: ', '').replace('Not detected publicly: ', ''));
}
function money(n) { return Number(n || 0).toLocaleString('en-US'); }
function issueSentence(issues) { if (!issues.length) return 'لقيت عدة نقاط تستحق المراجعة في مسار التحويل والظهور الرقمي.'; if (issues.length === 1) return `أوضح نقطة ظهرت لي في الفحص العام: ${issues[0]}.`; return `أوضح النقاط اللي ظهرت لي في الفحص العام: ${issues.join('، ')}.`; }
function businessContext(lead, audit) { if (!lead.website) return `وصلت لـ ${lead.name} من Google، وما قدرت أتحقق من موقع رسمي مستقل للنشاط ضمن المصادر العامة الحالية. لذلك الجزء الخاص بالموقع عندي تقديري محافظ، مو Audit كامل.`; const title = audit.evidence?.title; return title ? `راجعت حضور ${lead.name} على Google والموقع (${title}) بشكل فعلي.` : `راجعت حضور ${lead.name} على Google والموقع بشكل فعلي.`; }
function buildBreakdownLines(audit, includeMoney) { return (audit.opportunityBreakdown || []).slice(0, 5).map(item => { const r = item.annualRange || {}; return includeMoney ? `• ${item.service}: ${money(r.low)}–${money(r.high)} ريال سنويًا — ${item.issues?.slice(0, 2).join('، ') || ''}` : `• ${item.service}: ${item.issues?.slice(0, 2).join('، ') || ''}`; }); }
function ensureBookingLink(body, bookingUrl) { if (!bookingUrl || String(body).includes(bookingUrl)) return body; return `${String(body).trim()}\n\nإذا حابين نشوف المراجعة سوا، هذا رابط موعد قصير:\n${bookingUrl}`; }
function withQuality(message, { audit, bookingUrl }) { const quality = validateOutreach({ subject: message.subject, body: message.body, bookingUrl, audit }); return { ...message, quality }; }

function fallbackMessage({ lead, audit, bookingUrl }) {
  const issues = topIssues(audit); const route = lead.contactRoute || { channel: lead.contactEmail ? 'email' : 'research_required', destination: lead.contactEmail || null }; const context = businessContext(lead, audit); const gapLine = issueSentence(issues); const annual = audit.opportunity?.annualRange || { low: 0, high: 0 }; const showMoney = audit.opportunity?.displayEligible === true; const breakdown = buildBreakdownLines(audit, showMoney); const confidence = audit.opportunity?.confidence;
  const headline = showMoney && annual.high > 0 ? `بناءً على المراجعة والمدخلات التجارية المتاحة، قد تكون عندكم فرصة تحسين تقديرية بين ${money(annual.low)} و${money(annual.high)} ريال سنويًا${confidence ? ` بدرجة ثقة ${confidence}%` : ''}.` : 'فضلت ما أحط رقم مالي لأن البيانات العامة وحدها ما تكفي لتقدير مهني بالريال.';
  const body = `مرحبًا فريق ${lead.name}\n\n${context}\n\n${gapLine}\n\n${headline}${breakdown.length ? `\n\nالتفصيل حسب كل جزء:\n${breakdown.join('\n')}` : ''}\n\nمهم: الفحص يعتمد على بيانات عامة فقط. أي Integration ديناميكي مثل Meta Pixel أو Analytics أو روابط اجتماعية لا نقدر نثبت غيابه من HTML الخام، لذلك عدم رصده لا نعتبره مفقودًا.\n\nأنا ما أرسل لكم عرض تسويق عام. عندي المراجعة نفسها، وأقدر أوريكم بالضبط إيش ظهر وإيش يحتاج تحقق أعمق وإيش الأولوية.\n\n${bookingUrl ? `إذا حابين نشوفها سوا، هذا رابط موعد قصير:\n${bookingUrl}\n\n` : ''}محمد\nSahab Agency`;
  return withQuality({ subject: showMoney && annual.high > 0 ? `${lead.name}: فرصة تحسين تقديرية حتى ${money(annual.high)} ريال سنويًا` : `${lead.name}: ملاحظات من فحص نمو عام`, body, channel: route.channel === 'research_required' ? 'email' : route.channel, destination: route.destination || lead.contactEmail || null, generatedBy: 'rules', evidenceUsed: issues, requiresReview: true }, { audit, bookingUrl });
}

async function viaOpenAI({ lead, audit, bookingUrl, industry, location }) {
  const key = process.env.OPENAI_API_KEY; if (!key) return null; const showMoney = audit.opportunity?.displayEligible === true;
  const payload = { model: process.env.OPENAI_MODEL || 'gpt-5-mini', input: [{ role: 'system', content: `Write a concise Arabic B2B outbound email for a Saudi/Gulf business in a natural professional tone. Use only provided public evidence. Dynamic integrations such as Meta Pixel, Analytics, GTM, Instagram/Facebook links can be injected client-side; if the audit marks them unknown or does not positively detect them, NEVER call them missing. Never state ads are inactive or tracking is absent unless evidence explicitly proves it. ${showMoney ? 'A SAR opportunity range is allowed because commercial context passed the credibility gate; still label it estimated, not verified loss.' : 'DO NOT mention any SAR amount, revenue loss, opportunity amount, ticket value, lead volume, or financial range because commercial context did not pass the credibility gate.'} Do not invent traffic, spend, rankings, leads, revenue, customer behavior, ad status, or platform usage. No guarantees, hype, emojis, or spammy urgency. Keep subject under 90 characters if possible. If a booking URL is provided, include it exactly once near the end. Output valid JSON with subject and body only.` }, { role: 'user', content: JSON.stringify({ business: lead.name, website: lead.website, googleRating: lead.rating, reviewCount: lead.reviewCount, industry, location, auditMode: audit.auditMode, qualification: audit.qualification, contactRoute: lead.contactRoute, socials: lead.socials, auditScore: audit.score, issues: audit.issues, unknowns: audit.unknowns, evidence: audit.evidence, commercialProfile: showMoney ? audit.commercialProfile : { withheld: true }, opportunityEstimate: showMoney ? audit.opportunity : { displayEligible: false, withheldReason: audit.opportunity?.withheldReason }, opportunityBreakdown: audit.opportunityBreakdown?.map(x => ({ service: x.service, issues: x.issues })), bookingUrl }) }] };
  const response = await fetch('https://api.openai.com/v1/responses', { method: 'POST', headers: { Authorization: `Bearer ${key}`, 'Content-Type': 'application/json' }, body: JSON.stringify(payload), signal: AbortSignal.timeout(20000) });
  if (!response.ok) return null; const data = await response.json(); const text = data.output_text || data.output?.flatMap(x => x.content || []).find(x => x.type === 'output_text')?.text; if (!text) return null;
  const cleaned = text.trim().replace(/^```json\s*/i, '').replace(/```$/i, '').trim();
  try { const parsed = JSON.parse(cleaned); if (!parsed.subject || !parsed.body) return null; const candidate = withQuality({ subject: parsed.subject, body: ensureBookingLink(parsed.body, bookingUrl), channel: lead.contactRoute?.channel || (lead.contactEmail ? 'email' : 'research_required'), destination: lead.contactRoute?.destination || lead.contactEmail || null, generatedBy: 'openai', evidenceUsed: topIssues(audit), requiresReview: true }, { audit, bookingUrl }); return candidate.quality.ok ? candidate : null; } catch { return null; }
}

export async function buildOutreach(args) { const ai = await viaOpenAI(args).catch(() => null); if (ai) return ai; const fallback = fallbackMessage(args); return { ...fallback, qualityFallback: !ai }; }
