import { validateOutreach } from './messageGuard.js';

function topIssues(audit) {
  const severity = { high: 3, medium: 2, low: 1 };
  return (audit.issues || []).slice().sort((a, b) => (severity[b.severity] || 0) - (severity[a.severity] || 0)).slice(0, 3).map(issue => issue.title.replace('Missing or weak: ', '').replace('Not detected publicly: ', ''));
}
function money(n) { return Number(n || 0).toLocaleString('en-US'); }
function issueSentence(issues) { if (!issues.length) return 'الفحص ما أعطاني مشكلة سطحية أقدر أعتبرها مؤكدة، لذلك ركزت على فرص النمو المدعومة بهيكل المتجر نفسه.'; if (issues.length === 1) return `أوضح نقطة ظهرت لي في الفحص العام: ${issues[0]}.`; return `أوضح النقاط اللي ظهرت لي في الفحص العام: ${issues.join('، ')}.`; }
function platformName(bi={}) { return typeof bi.platform === 'string' ? bi.platform : (bi.platform?.name || ''); }
function businessContext(lead, audit) {
  if (!lead.website) return `وصلت لـ ${lead.name} من Google، وما قدرت أتحقق من موقع رسمي مستقل ضمن المصادر العامة الحالية.`;
  const bi = audit.businessIntelligence || {};
  const cats = (bi.categories || []).slice(0, 4).join('، ');
  const products = (bi.products || []).slice(0, 4).join('، ');
  const parts = [`راجعت ${lead.name} والموقع بشكل فعلي`];
  if (bi.industry) parts.push(`وفهمت النشاط كـ ${bi.industry}`);
  const platform = platformName(bi); if (platform) parts.push(`والمتجر يعمل على ${platform}`);
  if (bi.primaryRevenueMotion) parts.push(`ومسار الإيراد الأساسي هو ${bi.primaryRevenueMotion}`);
  if (cats) parts.push(`والأقسام الظاهرة تشمل ${cats}`);
  if (products) parts.push(`ومن المنتجات المرصودة ${products}`);
  return `${parts.join('، ')}.`;
}
function buildBreakdownLines(audit, includeMoney) { return (audit.opportunityBreakdown || []).slice(0, 5).map(item => { const r = item.annualRange || {}; return includeMoney ? `• ${item.service}: ${money(r.low)}–${money(r.high)} ريال سنويًا — ${item.issues?.slice(0, 2).join('، ') || ''}` : `• ${item.service}: ${item.issues?.slice(0, 2).join('، ') || ''}`; }); }
function ensureBookingLink(body, bookingUrl) { if (!bookingUrl || String(body).includes(bookingUrl)) return body; return `${String(body).trim()}\n\nإذا حابين نشوف المراجعة سوا، هذا رابط موعد قصير:\n${bookingUrl}`; }
function withQuality(message, { audit, bookingUrl }) { const quality = validateOutreach({ subject: message.subject, body: message.body, bookingUrl, audit }); return { ...message, quality }; }
function sanitizeEvidenceClaims(message, audit = {}) {
  const bi = audit.businessIntelligence || {}; const profile = audit.commercialProfile || {};
  const observed = Number(bi.priceStats?.sampleCount || 0) > 0 || Number(profile.observedPriceStats?.sampleCount || 0) > 0 || /observed_(site|core)_product_prices/i.test(String(profile.averageTicketSource || ''));
  if (observed) return message;
  const body = String(message.body || '').split(/(?<=[.!؟])\s+/).filter(sentence => !/(الأسعار|سعر|prices|pricing|price samples|observed prices)/i.test(sentence)).join(' '); return { ...message, body: body.replace(/observed product prices/gi, 'catalog structure and modeled ticket assumptions').replace(/public prices/gi, 'public catalog structure') };
}

function fallbackMessage({ lead, audit, bookingUrl, language = 'ar' }) {
  if (language === 'en') {
    const bi = audit.businessIntelligence || {}; const profile = audit.commercialProfile || {}; const opportunity = audit.opportunity || {}; const annual = opportunity.annualRange || { low: 0, high: 0 }; const showMoney = opportunity.displayEligible === true; const route = lead.contactRoute || {}; const plans = (audit.opportunityBreakdown || []).slice(0, 3).map(item => `• ${item.service}: ${item.problemEn || 'Specific improvement area observed'} Solution: ${item.solutionEn || 'Run a focused conversion experiment.'} Method: ${item.methodEn || 'Set a baseline, implement one change, and compare before and after.'} Measure: ${item.measurementEn || 'Track the conversion metric tied to this page.'}`); const body = `Hello ${lead.name} team,\n\nI reviewed ${lead.name} and its public website. The scan identified the business as ${bi.industry || 'a retail business'}${platformName(bi) ? ` on ${platformName(bi)}` : ''}, with ${bi.products?.slice(0, 4).join(', ') || 'a visible product/catalog structure'}.\n\n${showMoney ? `The modeled growth opportunity is ${money(annual.low)}–${money(annual.high)} SAR per year. This is a bounded growth model, not verified lost revenue.` : 'I am not presenting a financial number because the public evidence is not strong enough to defend one.'}\n\nSpecific findings and next actions:\n${plans.join('\n')}\n\nThe review uses public evidence only. Tracking tools are marked verified only when their code is positively observable; unknown does not mean missing.\n\nI am not sending a generic marketing proposal. The review is based on your actual site and can be walked through with your team.${bookingUrl ? `\n\nReview link: ${bookingUrl}` : ''}\n\nMohammed\nSahab Agency`; return withQuality({ subject: showMoney && annual.high > 0 ? `${lead.name}: modeled growth opportunity` : `${lead.name}: evidence-based website review`, body, channel: route.channel === 'research_required' ? 'email' : route.channel, destination: route.destination || lead.contactEmail || null, generatedBy: 'rules', evidenceUsed: plans, requiresReview: true }, { audit, bookingUrl });
  }
  const issues = topIssues(audit); const route = lead.contactRoute || { channel: lead.contactEmail ? 'email' : 'research_required', destination: lead.contactEmail || null }; const context = businessContext(lead, audit); const gapLine = issueSentence(issues); const annual = audit.opportunity?.annualRange || { low: 0, high: 0 }; const showMoney = audit.opportunity?.displayEligible === true; const breakdown = buildBreakdownLines(audit, showMoney); const confidence = audit.opportunity?.confidence; const bi = audit.businessIntelligence || {}; const profile = audit.commercialProfile || {};
  const headline = showMoney && annual.high > 0
    ? `بناءً على المنتجات والأسعار ومسار الشراء وهيكل المتجر اللي قدرنا نرصده، تظهر فرصة نمو تقديرية بين ${money(annual.low)} و${money(annual.high)} ريال سنويًا${confidence ? ` بدرجة ثقة ${confidence}%` : ''}.`
    : 'قدرت أفهم النشاط ومسار الشراء من الموقع، لكن مستوى الثقة التجاري الحالي ما يكفي إني أحط رقم مالي وأقدمه كأنه دقيق.';
  const modelLine = profile.averageTicketSource ? `مصدر نموذج قيمة الطلب: ${profile.averageTicketSource}${profile.observedPriceStats?.sampleCount ? ` من ${profile.observedPriceStats.sampleCount} عينة سعر عامة` : ''}.` : '';
  const body = `مرحبًا فريق ${lead.name}\n\n${context}\n\n${gapLine}\n\n${headline}${modelLine ? `\n${modelLine}` : ''}${breakdown.length ? `\n\nالتفصيل حسب كل جزء:\n${breakdown.join('\n')}` : ''}\n\nمهم: الفحص يعتمد على بيانات عامة فقط. أي Integration ديناميكي مثل Meta Pixel أو Analytics أو روابط اجتماعية إذا ما قدرنا نثبته علنًا، ما نعتبره مفقودًا ولا نحسب عليه فرصة مالية. ومسار المشاريع والشركات إذا كان موجودًا يُعامل كمسار ثانوي ما لم يثبت أنه الإيراد الأساسي.\n\nأنا ما أرسل لكم عرض تسويق عام. عندي المراجعة نفسها وأقدر أوريكم إيش ظهر فعليًا وإيش الأولوية التجارية بناءً على المتجر نفسه.\n\n${bookingUrl ? `إذا حابين نشوفها سوا، هذا رابط موعد قصير:\n${bookingUrl}\n\n` : ''}محمد\nSahab Agency`;
  return withQuality(sanitizeEvidenceClaims({ subject: showMoney && annual.high > 0 ? `${lead.name}: فرصة نمو تقديرية حتى ${money(annual.high)} ريال سنويًا` : `${lead.name}: ملاحظات مبنية على المتجر نفسه`, body, channel: route.channel === 'research_required' ? 'email' : route.channel, destination: route.destination || lead.contactEmail || null, generatedBy: 'rules', evidenceUsed: issues, requiresReview: true }, audit), { audit, bookingUrl });
}

async function viaOpenAI({ lead, audit, bookingUrl, industry, location }) {
  const key = process.env.OPENAI_API_KEY; if (!key) return null; const showMoney = audit.opportunity?.displayEligible === true; const bi = audit.businessIntelligence || {};
  const payload = { model: process.env.OPENAI_MODEL || 'gpt-5-mini', input: [{ role: 'system', content: `Write a concise B2B outbound email in the requested language (Arabic only when language=ar, English only when language=en) in a natural professional tone. First prove the business was understood from its website: exact business type, platform, products/categories, public pricing, primary revenue motion and secondary revenue paths. CRITICAL: if direct ecommerce exists with cart/checkout, treat direct ecommerce as the PRIMARY revenue motion. A B2B/project page is a SECONDARY revenue path unless the supplied evidence explicitly says otherwise; never collapse the entire business into B2B. Use only provided evidence. Dynamic integrations such as Meta Pixel, Analytics, GTM, Instagram/Facebook links can be injected client-side; if the audit marks them unknown or does not positively detect them, NEVER call them missing and NEVER infer that ads are inactive. ${showMoney ? 'A Saudi-riyal opportunity range is allowed because the business-specific commercial model passed its credibility gate. Explain it as a modeled growth range built from observed product prices, catalog structure, ecommerce path and bounded order/demand assumptions, never as verified loss.' : 'Do not mention a Saudi-riyal amount because the commercial confidence gate did not pass.'} Never invent traffic, spend, rankings, revenue, ad status, customer behavior, product prices, or platform usage. No guarantees, hype, emojis, or spammy urgency. Keep subject under 90 characters if possible. If a booking URL is provided, include it exactly once near the end. Output valid JSON with subject and body only.` }, { role: 'user', content: JSON.stringify({ business: lead.name, website: lead.website, googleRating: lead.rating, reviewCount: lead.reviewCount, requestedIndustry: industry, location, inferredBusinessIntelligence: bi, auditMode: audit.auditMode, qualification: audit.qualification, contactRoute: lead.contactRoute, socials: lead.socials, auditScore: audit.score, issues: audit.issues, unknowns: audit.unknowns, evidence: audit.evidence, commercialProfile: showMoney ? audit.commercialProfile : { withheld: true }, opportunityEstimate: showMoney ? audit.opportunity : { displayEligible: false, withheldReason: audit.opportunity?.withheldReason }, opportunityBreakdown: audit.opportunityBreakdown?.map(x => ({ service: x.service, issues: x.issues, annualRange: showMoney ? x.annualRange : undefined, evidenceClass:x.evidenceClass })), bookingUrl, language }) }] };
  const response = await fetch('https://api.openai.com/v1/responses', { method: 'POST', headers: { Authorization: `Bearer ${key}`, 'Content-Type': 'application/json' }, body: JSON.stringify(payload), signal: AbortSignal.timeout(20000) });
  if (!response.ok) return null; const data = await response.json(); const text = data.output_text || data.output?.flatMap(x => x.content || []).find(x => x.type === 'output_text')?.text; if (!text) return null;
  const cleaned = text.trim().replace(/^```json\s*/i, '').replace(/```$/i, '').trim();
  try { const parsed = JSON.parse(cleaned); if (!parsed.subject || !parsed.body) return null; if (args.language === 'en' && /[\u0600-\u06ff]/.test(`${parsed.subject} ${parsed.body}`)) return null; const candidate = withQuality(sanitizeEvidenceClaims({ subject: parsed.subject, body: ensureBookingLink(parsed.body, bookingUrl), channel: lead.contactRoute?.channel || (lead.contactEmail ? 'email' : 'research_required'), destination: lead.contactRoute?.destination || lead.contactEmail || null, generatedBy: 'openai', evidenceUsed: topIssues(audit), requiresReview: true }, audit), { audit, bookingUrl }); return candidate.quality.ok ? candidate : null; } catch { return null; }
}

export async function buildOutreach(args) { const ai = await viaOpenAI(args).catch(() => null); if (ai) return ai; const fallback = fallbackMessage(args); return { ...fallback, qualityFallback: !ai }; }

