import * as cheerio from 'cheerio';

const clean=s=>String(s||'').replace(/\s+/g,' ').trim();
const abs=(href,base)=>{try{return new URL(href,base).href.split('#')[0]}catch{return null}};
async function get(url,timeout=9000){try{const r=await fetch(url,{redirect:'follow',headers:{'user-agent':'Mozilla/5.0 (compatible; SahabTechnicalAudit/1.0)'},signal:AbortSignal.timeout(timeout)});return{ok:r.ok,status:r.status,url:r.url,html:(r.headers.get('content-type')||'').includes('text/html')?await r.text():'',headers:Object.fromEntries(r.headers.entries())}}catch(e){return{ok:false,status:null,url,html:'',error:e.message}}}
async function pagespeed(url,strategy){
  try{const u=new URL('https://www.googleapis.com/pagespeedonline/v5/runPagespeed');u.searchParams.set('url',url);u.searchParams.set('strategy',strategy);u.searchParams.set('category','performance');const key=process.env.PAGESPEED_API_KEY||process.env.GOOGLE_PAGESPEED_API_KEY||'';if(key)u.searchParams.set('key',key);const r=await fetch(u,{signal:AbortSignal.timeout(60000)});if(!r.ok){let detail='';try{const body=await r.json();detail=body?.error?.message||''}catch{}return{state:'unavailable',reason:`PageSpeed API HTTP ${r.status}${detail?`: ${detail}`:''}`};}const d=await r.json(),l=d.lighthouseResult||{},audits=l.audits||{},score=l.categories?.performance?.score;const issues=Object.values(audits).filter(a=>a.score!=null&&a.score<1&&['diagnostic','load-opportunity','metric'].some(x=>String(a.details?.type||'').includes(x)||a.title)).sort((a,b)=>(a.score??1)-(b.score??1)).slice(0,5).map(a=>({title:a.title,score:a.score,displayValue:a.displayValue||null,description:clean(a.description).slice(0,240)}));return{state:'measured',score:score==null?null:Math.round(score*100),strategy,fetchTime:l.fetchTime||null,metrics:{fcp:audits['first-contentful-paint']?.displayValue||null,lcp:audits['largest-contentful-paint']?.displayValue||null,cls:audits['cumulative-layout-shift']?.displayValue||null,tbt:audits['total-blocking-time']?.displayValue||null,speedIndex:audits['speed-index']?.displayValue||null},topIssues:issues};}catch(e){return{state:'unavailable',reason:e.message}}
}
function inspectPage(html,url,type='other'){
  const $=cheerio.load(html),body=clean($('body').text()),source=html,links=[];$('a[href]').each((_,x)=>{const u=abs($(x).attr('href'),url);if(u)links.push(u)});
  const images=$('img').map((_,x)=>({src:abs($(x).attr('src')||$(x).attr('data-src'),url),alt:clean($(x).attr('alt')),loading:$(x).attr('loading')||null,width:$(x).attr('width')||null,height:$(x).attr('height')||null})).get();
  const scripts=$('script[src]').map((_,x)=>$(x).attr('src')).get(),styles=$('link[rel="stylesheet"]').map((_,x)=>$(x).attr('href')).get();
  const heading=$('h1,h2,h3,h4').map((_,x)=>({tag:x.name,text:clean($(x).text()).slice(0,100)})).get();
  const schemas=[];$('script[type="application/ld+json"]').each((_,x)=>{try{const d=JSON.parse($(x).html()||'{}');const walk=o=>{if(!o||typeof o!=='object')return;if(o['@type'])schemas.push(Array.isArray(o['@type'])?o['@type'].join(','):o['@type']);Object.values(o).forEach(v=>Array.isArray(v)?v.forEach(walk):walk(v))};walk(d)}catch{}});
  const text=`${body} ${source}`.toLowerCase(),title=clean($('title').text()),meta=clean($('meta[name="description"]').attr('content')),canonical=$('link[rel="canonical"]').attr('href')||null;
  return{url,type,title,titleLength:title.length,metaDescription:meta,metaLength:meta.length,h1Count:$('h1').length,h1:clean($('h1').first().text()),headingHierarchy:heading,wordCount:body?body.split(/\s+/).length:0,images:imageStats(images),scripts:assetStats(scripts),styles:assetStats(styles),altMissing:images.filter(x=>!x.alt).length,imageFormats:images.map(x=>String(x.src||'').split('?')[0].split('.').pop().toLowerCase()).filter(Boolean),lazyImages:images.filter(x=>x.loading==='lazy'||x.src==null).length,canonical,hasBreadcrumb:/breadcrumb|breadcrumbs|مسار التنقل|الرئيسية/.test(text),schemas:[...new Set(schemas)],links:uniq(links),urlHasQuery:locationHasQuery(url),content:body};
}
function uniq(a){return[...new Set(a.filter(Boolean))]};function locationHasQuery(u){try{return Boolean(new URL(u).search)}catch{return false}}
function imageStats(a){return{count:a.length,missingAlt:a.filter(x=>!x.alt).length,withDimensions:a.filter(x=>x.width&&x.height).length,lazy:a.filter(x=>x.loading==='lazy').length,nonModern:a.filter(x=>/\.(jpg|jpeg|png|gif)(\?|$)/i.test(x.src||'')).length};}
function assetStats(a){return{count:a.length,unminified:a.filter(x=>/\.js(?:\?|$)|\.css(?:\?|$)/i.test(x)&&!/[.-](min|prod)\./i.test(x)).length,renderBlocking:a.length};}
export async function buildTechnicalAudit({url,requestedUrl=url,html='',bi={}}={}){
  const root=inspectPage(html,url,'home');
  const origin=new URL(url).origin;
  const [robots,sitemap,mobile,desktop]=await Promise.all([get(`${origin}/robots.txt`,7000),get(`${origin}/sitemap.xml`,7000),pagespeed(url,'mobile'),pagespeed(url,'desktop')]);
  const hreflang=(()=>{const $=cheerio.load(html);return $('link[rel="alternate"][hreflang]').map((_,x)=>({lang:$(x).attr('hreflang'),href:$(x).attr('href')})).get()})();
  const mixed=[...html.matchAll(/(?:src|href)=['"](http:\/\/[^'"]+)/gi)].map(x=>x[1]).slice(0,10);
  const redirectChain=robots.url!==`${origin}/robots.txt`||sitemap.url!==`${origin}/sitemap.xml`;
  const brokenInternal=[];for(const u of root.links.filter(x=>{try{return new URL(x).origin===origin}catch{return false}}).slice(0,25)){const r=await get(u,5000);if(r.status>=400)brokenInternal.push({url:u,status:r.status})}
  const speedIssues=[...(mobile.topIssues||[]).map(x=>({...x,device:'mobile'})),...(desktop.topIssues||[]).map(x=>({...x,device:'desktop'}))].slice(0,5);
  const store=bi.siteMode==='ecommerce_store'||bi.siteMode==='service_commerce';
  const finalUrl=root.url,requestedHost=new URL(requestedUrl).hostname.replace(/^www\./,''),finalHost=new URL(finalUrl).hostname.replace(/^www\./,'');
  const technical={requestedUrl,finalUrl,redirect:{observed:requestedUrl!==finalUrl,domainChanged:requestedHost!==finalHost,requestedHost,finalHost},pagespeed:{mobile,desktop,topIssues:speedIssues},robots:{url:`${origin}/robots.txt`,status:robots.status,found:robots.ok,valid:robots.ok&&/user-agent/i.test(robots.html),sitemaps:(robots.html.match(/^sitemap:\s*\S+/gim)||[])},sitemap:{url:`${origin}/sitemap.xml`,status:sitemap.status,found:sitemap.ok,urlCount:(sitemap.html.match(/<loc>/gi)||[]).length},security:{https:url.startsWith('https://')&&finalUrl.startsWith('https://'),mixedContent:mixed,redirectChainObserved:redirectChain},pages:[root],onPage:{title:{value:root.title,length:root.titleLength,ideal:root.titleLength>=50&&root.titleLength<=60},metaDescription:{value:root.metaDescription,length:root.metaLength,ideal:root.metaLength>=150&&root.metaLength<=160},h1:{count:root.h1Count,value:root.h1},headings:root.headingHierarchy,images:root.images,scripts:root.scripts,styles:root.styles,wordCount:root.wordCount,canonical:root.canonical,hreflang,schemas:root.schemas,breadcrumbs:root.hasBreadcrumb},ux:{internalLinkCount:root.links.length,brokenInternal,queryUrl:root.urlHasQuery,searchVisible:/بحث|search/i.test(root.content),filterVisible:/فلتر|filter|تصفية/i.test(root.content),sortingVisible:/ترتيب|sort|الأحدث|الأكثر مبيعًا/i.test(root.content),stickyCandidate:/sticky|position:\s*fixed/i.test(html),footerLinks:cheerio.load(html)('footer a').length,custom404:null},ecommerce:store?{productSignals:bi.funnelSignals||{},paymentMethods:bi.funnelSignals?.installmentDetected||false,categoryCount:bi.pageInventory?.categoryLinks||0,productCount:bi.pageInventory?.productLinks||0}:null,localSeo:bi.googleBusinessProfile||null,classification:{siteMode:bi.siteMode||null,industry:bi.industry||null,evidence:bi.evidence||null}};
  if(technical.redirect.domainChanged) technical.summary={domainWarning:`Requested host ${requestedHost} redirected to ${finalHost}; verify this is the intended business domain before using the report.`};
  technical.summary={...(technical.summary||{}),measured:['PageSpeed mobile/desktop','HTTP/security','robots/sitemap','homepage on-page HTML','internal-link status sample'].filter((_,i)=>i<5),unavailable:['indexed page count via site: search','Google Mobile-Friendly Test API','Google Ads spend/ROAS and private event data'],storeSpecific:store,disclaimer:'Only public HTML, HTTP responses, PageSpeed output and connected Google data are used. Missing public markers are not proof of absence.'};
  return technical;
}
